- name: Kubernetes Controlplane Setup
  hosts: k8s_controlplane
  environment: "{{ env_vars }}"  
  become: true
  vars_files:
      - vars/lab.yml    
  tasks:

    - name: Download Metallb manifest
      get_url:
        url: "https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml"
        dest: /tmp/metallb.yml     

    - name: Apply Metallb manifest
      command: kubectl apply -f /tmp/metallb.yml  