- name: Kubernetes Controlplane Setup
  hosts: k8s_controlplane
  environment: "{{ env_vars }}"  
  become: true
  vars_files:
      - vars/lab.yml    
  tasks:

    - name: Deploy Longhorn secret
      include_role:
        name: longhorn_secret
      vars:
        secret: "{{ longhorn_secret }}"