- name: Kubernetes Controlplane Setup
  hosts: k8s_controlplane
  environment: "{{ env_vars }}"  
  become: true
  vars_files:
      - vars/lab.yml    
  tasks:

    - name: Create Metallb address pool
      include_role:
        name: custom_resource
      vars:
        resource: "{{ metallb_address }}"

    - name: Create Metallb advertisement
      include_role:
        name: custom_resource
      vars:
        resource: "{{ metallb_advertise }}"